- name: Create storage account
  hosts: localhost
  connection: local
  tasks:
  - name: Create account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storage_name }}"
      account_type: "{{ acc_type }}"
